export interface Blueprint {
    "uid": string;
    "Name_tw": string;
    "Name_en": string;
    "webtype": string;
    "Name": string;
    "Type": string;
    "UnlockPrerequisite": string | null;
    "ResearchScrolls": number | string;
    "AntiqueTokens": number | string;
    "Tier": number;
    "Value": number;
    "CraftingTime(seconds)": number;
    "CraftingTime(formatted)": string;
    "Value/CraftingTime": number;
    "MerchantXP": number;
    "MerchantXP/CraftingTime": number;
    "WorkerXP": number;
    "FusionXP": number;
    "Favor": number;
    "AirshipPower": number;
    "RequiredWorker": string;
    "WorkerLevel": number;
    "RequiredWorker2": string;
    "WorkerLevel2": number | string | null;
    "RequiredWorker3": string;
    "WorkerLevel3": number | string | null;
    "Component": string;
    "ComponentQuality": string;
    "AmountNeeded": number | string | null;
    "Component2": string;
    "ComponentQuality2": string;
    "AmountNeeded2": number | string | null;
    "ATK": number | string;
    "DEF": number | string;
    "HP": number | string;
    "EVA": number | string;
    "CRIT": number | string;
    "ElementalAffinity": string;
    "SpiritAffinity": string;
    "CraftingUpgrade1": string;
    "CraftsNeeded": number;
    "CraftingUpgrade2": string;
    "CraftsNeeded2": number;
    "CraftingUpgrade3": string;
    "CraftsNeeded3": number;
    "CraftingUpgrade4": string;
    "CraftsNeeded4": number;
    "CraftingUpgrade5": string;
    "CraftsNeeded5": number;
    "AscensionUpgrade1": string;
    "ShardsNeeded": number;
    "AscensionUpgrade2": string;
    "ShardsNeeded2": number;
    "AscensionUpgrade3": string;
    "ShardsNeeded3": number;
    "DiscountEnergy": number;
    "SurchargeEnergy": number;
    "SuggestEnergy": number;
    "SpeedUpEnergy": number;
    "Iron": number | string;
    "Wood": number | string;
    "Leather": number | string;
    "Herbs": number | string;
    "Steel": number | string;
    "Ironwood": number | string;
    "Cloth": number | string;
    "Oil": number | string;
    "Gems": number | string;
    "Mana": number | string;
    "Essence": number | string;
}
