export interface Blueprint {
    "Name": string;
    "Type": string;
    "Unlock Prerequisite": string | null;
    "Research Scrolls": number | string;
    "Antique Tokens": number | string;
    "Tier": number;
    "Value": number;
    "Crafting Time (seconds)": number;
    "Crafting Time (formatted)": string;
    "Value / Crafting Time": number;
    "Merchant XP": number;
    "Merchant XP / Crafting Time": number;
    "Worker XP": number;
    "Fusion XP": number;
    "Favor": number;
    "Airship Power": number;
    "Required Worker": string;
    "Worker Level": number;
    "Required Worker 2": string;
    "Worker Level 2": number | string | null;
    "Required Worker 3": string;
    "Worker Level 3": number | string | null;
    "Component": string;
    "Component Quality": string;
    "Amount Needed": number | string | null;
    "Component 2": string;
    "Component Quality 2": string;
    "Amount Needed 2": number | string | null;
    "ATK": number | string;
    "DEF": number | string;
    "HP": number | string;
    "EVA": number | string;
    "CRIT": number | string;
    "Elemental Affinity": string;
    "Spirit Affinity": string;
    "Crafting Upgrade 1": string;
    "Crafts Needed": number;
    "Crafting Upgrade 2": string;
    "Crafts Needed 2": number;
    "Crafting Upgrade 3": string;
    "Crafts Needed 3": number;
    "Crafting Upgrade 4": string;
    "Crafts Needed 4": number;
    "Crafting Upgrade 5": string;
    "Crafts Needed 5": number;
    "Ascension Upgrade 1": string;
    "Shards Needed": number;
    "Ascension Upgrade 2": string;
    "Shards Needed 2": number;
    "Ascension Upgrade 3": string;
    "Shards Needed 3": number;
    "Discount Energy": number;
    "Surcharge Energy": number;
    "Suggest Energy": number;
    "Speed Up Energy": number;
    "Iron": number | string;
    "Wood": number | string;
    "Leather": number | string;
    "Herbs": number | string;
    "Steel": number | string;
    "Ironwood": number | string;
    "Cloth": number | string;
    "Oil": number | string;
    "Gems": number | string;
    "Mana": number | string;
    "Essence": number | string;
}
